### ISSUE TITLE
partial incompatibility with pyenv

### ISSUE THREAD

**Issue by ssbarnea** [dolph/rtox#2]
I observed that if the remote machine has pyenv installed, running rtox is likely to fail in a very weird mode.

```
$ rtox                                                                                                                                                                                          [21:27:35]
Syncing the local repository to the remote host...
docs recreate: /root/.rtox/e9c7053ae04d70450e64e7c4cb238a3a9c0e9796/.tox/docs
No handlers could be found for logger "tox_pyenv"
ERROR: invocation failed (exit code 1), logfile: /root/.rtox/e9c7053ae04d70450e64e7c4cb238a3a9c0e9796/.tox/docs/log/docs-0.log
ERROR: actionid: docs
msg: getenv
cmdargs: ['/usr/bin/python', '-m', 'virtualenv', '--python', '/usr/bin/python', 'docs']

Already using interpreter /usr/bin/python
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 2328, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 925, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 1132, in install_python
    copy_required_modules(home_dir, symlink)
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 1063, in copy_required_modules
    copyfile(filename, dst_filename, symlink)
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 354, in copyfile
    copyfileordir(src, dest, symlink)
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 331, in copyfileordir
    shutil.copy2(src, dest)
  File "/usr/lib64/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib64/python2.7/shutil.py", line 69, in copyfile
    raise Error("`%s` and `%s` are the same file" % (src, dst))
shutil.Error: `/usr/lib64/python2.7/UserDict.py` and `/root/.rtox/e9c7053ae04d70450e64e7c4cb238a3a9c0e9796/.tox/docs/lib64/python2.7/UserDict.py` are the same file

ERROR: Error creating virtualenv. Note that some special characters (e.g. ':' and unicode symbols) in paths are not supported by virtualenv. Error details: InvocationError('/usr/bin/python -m virtualenv --python /usr/bin/python docs (see /root/.rtox/e9c7053ae04d70450e64e7c4cb238a3a9c0e9796/.tox/docs/log/docs-0.log)', 1)
```

I mention that I did run tox manually on remove machine and it works well, even from the save folder as the one created by rtox.

Some environments work, but some do not. One that is broken is a basic one like:
```
[testenv:docs]
commands = python setup.py build_sphinx {posargs}
```

Remove machine has these pyenvs installed:
```
pyenv versions
* system (set by /root/.python-version)
* 3.4.7 (set by /root/.python-version)
* 3.5.5 (set by /root/.python-version)
* 3.6.4 (set by /root/.python-version)
```

**Comment by ssbarnea** [comment]
This is now tracked at https://github.com/pycontribs/rtox/issues/3
